#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src", "version.ts");

// The commit hash is injected at build/publish time via the GIT_COMMIT_HASH env
// var (set in CI — see create_release_sdk.yml), the same convention as the
// backend's build.rs. It is intentionally NOT derived from `git rev-parse` here:
// version.ts is committed, so baking HEAD in would make it dirty after every
// local build. Defaults to "unknown" for local/dev builds.
const commitHash = (process.env.GIT_COMMIT_HASH ?? "").trim() || "unknown";

const contents = `// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on \`npm version\` and \`npm run build\`.
// SDK_COMMIT_HASH is injected from the GIT_COMMIT_HASH env var at build time.
export const SDK_NAME = "${pkg.name.replace(/^@[^/]+\//, "")}";
export const SDK_VERSION = "${pkg.version}";
export const SDK_COMMIT_HASH = "${commitHash}";
export const CLIENT_AGENT = \`\${SDK_NAME}/\${SDK_VERSION}\`;
`;

writeFileSync(target, contents);
console.log(
  `✓ src/version.ts synced to ${pkg.version} (${commitHash.slice(0, 7)})`,
);
