#!/usr/bin/env node
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const target = join(root, "src", "version.ts");

// Captured at (pre)build time so the published dist carries the commit it was
// built from. In CI the publish build runs from the merged release commit.
// Falls back to "unknown" when git isn't available (e.g. building outside a
// checkout); consumers install the pre-generated dist, so this only runs here.
let commitHash = "unknown";
try {
  commitHash = execSync("git rev-parse HEAD", {
    cwd: root,
    stdio: ["ignore", "pipe", "ignore"],
  })
    .toString()
    .trim();
} catch {
  // not a git checkout — leave as "unknown"
}

const contents = `// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on \`npm version\` and \`npm run build\`.
export const SDK_NAME = "${pkg.name.replace(/^@[^/]+\//, "")}";
export const SDK_VERSION = "${pkg.version}";
export const SDK_COMMIT_HASH = "${commitHash}";
export const CLIENT_AGENT = \`\${SDK_NAME}/\${SDK_VERSION}\`;
`;

writeFileSync(target, contents);
console.log(
  `✓ src/version.ts synced to ${pkg.version} (${commitHash.slice(0, 7)})`,
);
