/**
 * EVM utilities for Lendaswap.
 *
 * Provides helpers for encoding call data to interact with EVM HTLC contracts.
 */

export {
  buildCollabRefundEvmDigest,
  buildCollabRefundEvmTypedData,
  buildEip2612PermitDigest,
  buildNativeRedeemDigest,
  buildPermit2FundingDigest,
  buildPermit2TypedData,
  buildRedeemCalls,
  buildRedeemDigest,
  type CollabRefundEvmDigestParams,
  type CollabRefundEvmTypedData,
  type CoordinatorCall,
  computeCoordinatorCallsHash,
  type Eip2612PermitParams,
  type ExecuteAndCreateCallData,
  type ExecuteAndCreateWithPermit2Params,
  encodeDepositsCallData,
  encodeExecuteAndCreateWithPermit2,
  encodeNativeExecuteAndCreate,
  encodeNativeRefundTo,
  encodeRedeemAndExecute,
  encodeRefundAndExecute,
  encodeRefundTo,
  keccak256,
  NATIVE_TOKEN_ADDRESS,
  type NativeExecuteAndCreateCallData,
  type NativeExecuteAndCreateParams,
  type NativeRedeemDigestParams,
  type NativeRefundToParams,
  PERMIT2_ADDRESS,
  type Permit2FundingParams,
  type Permit2SignedFundingCallData,
  type Permit2TypedData,
  type RedeemAndExecuteCallData,
  type RedeemAndExecuteParams,
  type RedeemDigestParams,
  type RefundAndExecuteParams,
  type RefundToParams,
  type UnsignedPermit2FundingData,
} from "./coordinator.js";
export {
  type ApproveCallData,
  buildEvmHtlcCallData,
  type CreateSwapCallData,
  type CreateSwapParams,
  decodeSwapCreatedLog,
  encodeApproveCallData,
  encodeCreateSwapCallData,
  encodeHtlcErc20CreateCallData,
  encodeHtlcErc20IsActiveCallData,
  encodeHtlcErc20RefundCallData,
  encodeHtlcNativeRefundCallData,
  encodeRefundSwapCallData,
  findSwapCreated,
  type HtlcErc20CreateCallData,
  type HtlcErc20CreateParams,
  type HtlcErc20RefundCallData,
  type HtlcErc20RefundParams,
  type HtlcNativeRefundParams,
  normalizeBytes32,
  type RefundSwapCallData,
  type SwapCreatedFilter,
  type SwapCreatedLog,
  uuidToBytes32,
} from "./htlc.js";
export {
  isKernelDelegation,
  KERNEL_DELEGATION_TARGET,
  kernelErc1271Digest,
  parseEip7702Delegation,
  wrapKernelErc1271Signature,
} from "./kernel.js";
export { deriveEvmAddress, signEvmDigest } from "./signing.js";
export {
  type EIP712TypedData,
  type EvmSigner,
  isUserRejection,
  type ReceiptLog,
  SimulationRevertError,
  type TxReceipt,
} from "./wallet.js";
