export const VERSION = "0.0.1";

// API types
export type {
  ApiClient,
  ApiClientOptions,
  ArkadeToEvmSwapRequest,
  ArkadeToEvmSwapResponse,
  ArkadeToLightningSwapResponse,
  BitcoinToEvmSwapRequest,
  BtcToArkadeSwapResponse,
  Chain,
  ClaimGaslessRequest,
  ClaimGaslessResponse,
  components,
  EvmToArkadeSwapResponse,
  EvmToBitcoinSwapRequest,
  EvmToBitcoinSwapResponse,
  EvmToLightningSwapResponse,
  GetSwapResponse,
  LightningToArkadeSwapResponse,
  LightningToEvmSwapResponse,
  // Types
  paths,
  QuoteResponse,
  ServiceStatus,
  StatusResponse,
  SwapPairInfo,
  SwapPairsResponse,
  SwapStatus,
  TokenId,
  TokenInfo,
  TokenInfos,
} from "./api/client.js";
// API client
export { createApiClient } from "./api/client.js";
// Arkade VHTLC query utilities
export {
  type GetVhtlcAmountsParams,
  getVhtlcAmounts,
  type VhtlcAmounts,
  type VtxoStatus,
} from "./arkade.js";
// CCTP (Cross-Chain Transfer Protocol) utilities
export {
  type AttestationResponse,
  type AttestationResult,
  type AttestationStatus,
  addressToBytes32,
  type BridgeParams,
  type BurnResult,
  bytes32ToAddress,
  CCTP_DOMAINS,
  type CctpChainName,
  type CctpMessageResult,
  type CctpMessageStatus,
  computeCctpFastFee,
  EURC_ADDRESSES,
  type FetchAttestationOptions,
  type FetchCctpFeeOptions,
  FINALITY_FAST,
  FINALITY_STANDARD,
  FORWARDING_FEE_ETHEREUM,
  FORWARDING_FEE_OTHER,
  FORWARDING_SERVICE_HOOK_DATA,
  fetchAttestation,
  fetchCctpFee,
  getDomain,
  IRIS_API_MAINNET,
  IRIS_API_TESTNET,
  type IrisFeeEntry,
  type IrisForwardFeeTiers,
  isValidSolanaAddress,
  MESSAGE_TRANSMITTER_ADDRESSES,
  MESSAGE_TRANSMITTER_V2,
  type MintResult,
  needsBridge,
  solanaAddressToBytes32,
  TOKEN_MESSENGER_ADDRESSES,
  TOKEN_MESSENGER_V2,
  type TrackCctpMessageOptions,
  trackCctpMessage,
  USAT_ADDRESSES,
  USDC_ADDRESSES,
} from "./cctp/index.js";
// CCTP source-side inbound (any-chain USDC → Arbitrum → BTC)
export {
  type AaConfig,
  type ApproveAndBurnParams,
  type ApproveAndBurnResult,
  addressToBytes32Hex,
  approveAndBurn,
  type BatchCall,
  type BuildCctpInboundBatchParams,
  type BuiltBatch,
  buildCctpInboundBatch,
  buildDomainSeparator,
  CCTP_STANDARD_ONLY_CHAIN_IDS,
  CCTP_VIEM_CHAINS,
  type CctpFundSwapContext,
  type CctpFundSwapParams,
  type CctpFundSwapResult,
  CctpInboundClient,
  type CctpInboundClientConfig,
  type CctpProgressStep,
  CHAIN_ID_TO_CCTP_NAME,
  type CreateSwapSmartAccountClientParams,
  cctpFundSwap,
  cctpMetaForChainId,
  createSwapSmartAccountClient,
  type DepositForBurnParams,
  DIRECT_SOURCE_CHAIN_IDS,
  encodeDepositForBurn,
  finalityForChainId,
  getCctpViemChain,
  getCctpViemChainByName,
  isCctpOnlySource,
  MAX_UINT256,
  type RecoverCctpInboundContext,
  type RecoverCctpInboundParams,
  type RecoverCctpInboundResult,
  type RecoveryProgress,
  recoverCctpInbound,
  type SignEip2612Params,
  type SignedEip2612Permit,
  type SignedPermit2Witness,
  type SignPermit2Params,
  type SignTypedDataFn,
  type SimulateBatchCallsArgs,
  type SubmitUserOpContext,
  type SubmitUserOpParams,
  type SubmitUserOpResult,
  signEip2612Permit,
  signPermit2Witness,
  simulateBatchCalls,
  submitCctpInboundUserOp,
  USDC_DOMAIN_FIELDS,
  type UseropCalldataResponse,
} from "./cctp-inbound/index.js";
export type {
  ArkadeClaimOptions,
  BitcoinToArkadeSwapOptions,
  BitcoinToArkadeSwapResult,
  BitcoinToEvmSwapOptions,
  BitcoinToEvmSwapResponse,
  BitcoinToEvmSwapResult,
  BtcToEvmSwapOptions,
  ClaimGaslessResult,
  ClaimOptions,
  ClaimResult,
  ClientConfig,
  CreateSwapOptions,
  CreateSwapResult,
  EthereumClaimData,
  EvmChain,
  EvmFundingCallData,
  EvmToArkadeSwapGenericOptions,
  EvmToArkadeSwapGenericResult,
  EvmToArkadeSwapOptions,
  EvmToArkadeSwapResult,
  EvmToBitcoinSwapOptions,
  EvmToBitcoinSwapResult,
  EvmToLightningSwapOptions,
  OnchainRefundOptions,
  RecoverAllSwapsOptions,
  RecoverAllSwapsResult,
  RecoverAllSwapsStopReason,
  RecoverSwapsOptions,
  RecoverSwapsResult,
  RefundOptions,
  RefundResult,
  SupportAgentInfo,
  UsdcBridgeParams,
} from "./client.js";
// Main client
export { Client, ClientBuilder } from "./client.js";
// Escrow signing utilities
export {
  getArkTxid,
  type SignedEscrowDelegate,
  type SignedEscrowTx,
  signEscrowArkTx,
  signEscrowCheckpoints,
  signEscrowDelegate,
} from "./escrow/index.js";
// EVM HTLC utilities
export {
  type ApproveCallData,
  buildEvmHtlcCallData,
  buildPermit2TypedData,
  type CoordinatorCall,
  type CreateSwapCallData,
  type CreateSwapParams,
  deriveEvmAddress,
  type EvmSigner,
  type ExecuteAndCreateWithPermit2Params,
  encodeApproveCallData,
  encodeCreateSwapCallData,
  encodeExecuteAndCreateWithPermit2,
  encodeHtlcErc20CreateCallData,
  type HtlcErc20CreateCallData,
  type HtlcErc20CreateParams,
  isUserRejection,
  PERMIT2_ADDRESS,
  type Permit2TypedData,
  signEvmDigest,
  type TxReceipt,
  type UnsignedPermit2FundingData,
} from "./evm/index.js";
export {
  createConsoleLogger,
  createSdkLogger,
  type LogContext,
  type Logger,
  type LoggerOptions,
  type LogLevel,
  type LogRecord,
  noopLogger,
  redactLogValue,
  SdkLogger,
} from "./logging.js";
export {
  calculateSourceAmount,
  calculateTargetAmount,
  computeExchangeRate,
} from "./price-calculations.js";
// Redeem module (Arkade claim)
export {
  type ArkadeClaimParams,
  type ArkadeClaimResult,
  buildArkadeClaim,
} from "./redeem/index.js";
// Refund module
export {
  type BitcoinNetwork,
  buildOnchainClaimTransaction,
  buildOnchainRefundTransaction,
  computeHash160,
  type OnchainClaimParams,
  type OnchainClaimResult,
  type OnchainRefundParams,
  type OnchainRefundResult,
  verifyHtlcAddress,
} from "./refund/index.js";
export type { SwapParams } from "./signer/index.js";
// Signer (HD wallet key derivation)
export { bytesToHex, hexToBytes, Signer } from "./signer/index.js";
// IndexedDB storage (browser)
export {
  IdbSwapStorage,
  IdbWalletStorage,
  idbStorageFactory,
} from "./storage/idb.js";
export type {
  StorageFactory,
  StoredSwap,
  SwapStorage,
  WalletStorage,
} from "./storage/index.js";
// Storage interfaces and implementations
export {
  InMemorySwapStorage,
  InMemoryWalletStorage,
  inMemoryStorageFactory,
  SWAP_STORAGE_VERSION,
} from "./storage/index.js";
// Token helpers and constants
export {
  Asset,
  BTC_ARKADE,
  BTC_ARKADE_INFO,
  BTC_LIGHTNING,
  BTC_LIGHTNING_INFO,
  BTC_ONCHAIN,
  BTC_ONCHAIN_INFO,
  getBridgeTargetChain,
  getCctpBridgeTokens,
  getUsdt0BridgeTokens,
  isArbitrumToken,
  isArkade,
  isAvalancheToken,
  isBaseToken,
  isBridgeOnlyChain,
  isBtc,
  isBtcOnchain,
  isBtcPegged,
  isCctpUsdc,
  isEthereumToken,
  isEvmToken,
  isLightning,
  isLineaToken,
  isOptimismToken,
  isPolygonToken,
  isSolanaToken,
  isSonicToken,
  isSourceEvmChain,
  type TokenInput,
  toChain,
  toChainName,
} from "./tokens.js";
export { type GetUsdPricesOptions, getUsdPrices } from "./usd-price.js";
// USDT0 bridge (LayerZero OFT) utilities
export {
  getEid,
  getLzExplorerUrl,
  getLzMessageStatus,
  type LayerZeroMessageResult,
  type LayerZeroMessageStatus,
  LZ_EIDS,
  needsBridge as usdt0NeedsBridge,
  type TrackLzMessageOptions,
  trackLzMessage,
  USDT0_ADDRESSES,
  type Usdt0ChainName,
} from "./usdt0-bridge/index.js";
export type { SwapStatusHandler, SwapStatusWatcher } from "./ws.js";
