// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on `npm version` and `npm run build`.
export const SDK_NAME = "lendaswap-sdk-pure";
export const SDK_VERSION = "0.2.42";
export const CLIENT_AGENT = `${SDK_NAME}/${SDK_VERSION}`;
