// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on `npm version` and `npm run build`.
// SDK_COMMIT_HASH is injected from the GIT_COMMIT_HASH env var at build time.
export const SDK_NAME = "lendaswap-sdk-pure";
export const SDK_VERSION = "0.4.0";
export const SDK_COMMIT_HASH = "unknown";
export const CLIENT_AGENT = `${SDK_NAME}/${SDK_VERSION}`;
