// Generated by scripts/sync-version.mjs — do not edit by hand.
// Kept in sync with package.json on `npm version` and `npm run build`.
// SDK_COMMIT_HASH is injected from the GIT_COMMIT_HASH env var at build time.
// DEFAULT_AA_* are injected from AA_BUNDLER_URL / AA_POLICY_ID at publish time.
export const SDK_NAME = "lendaswap-sdk-pure";
export const SDK_VERSION = "2.3.0";
export const SDK_COMMIT_HASH = "unknown";
export const SATORA_SERVER_VERSION = "0.3.14";
export const CLIENT_AGENT = `${SDK_NAME}/${SDK_VERSION}`;
export const DEFAULT_AA_BUNDLER_URL = "";
export const DEFAULT_AA_POLICY_ID = "";
